[project]
name = "api-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deno>=2.5.6",
    "yt-dlp>=2025.11.12",
]
